[project]
name = "2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flax>=0.10.4",
    "jax==0.4.38",
    "matplotlib>=3.10.5",
    "optax>=0.2.5",
    "orbax>=0.1.9",
]
